package models

import (
	"errors"

	"github.com/gbadali/lenslocked.com/hash"

	"github.com/gbadali/lenslocked.com/rand"

	"golang.org/x/crypto/bcrypt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

// TODO: remove this
const hmacSecretKey = "secret-hmac-key"

// I haven't implemented testing so I am just doing a little bit here.
var _ UserDB = &userGorm{}
var _ UserService = &userService{}

var (
	// ErrNotFound is returned when a resource cannot be found
	// in the database.
	ErrNotFound = errors.New("models: resource not found")
	// ErrIDInvalid is used when we can't find the user
	ErrIDInvalid = errors.New("models: ID provided was invalid")
	// ErrPasswordIncorrect is returned when an invalid password
	// is used attempting to authnticate a user.
	ErrPasswordIncorrect = errors.New("models: incorrect password provided")
	userPwPepper         = "Secret-random-string"
)

// UserDB is used to interact with the users database.
//
// For pretty much all single user queries:
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong.  This may not be
// an error generated by the models package.
//
// For single user queries, any error but ErrNotFound should
// probabbly result in a 500 error until we make "public"
// facing errors.
type UserDB interface {
	// Methods for querying single users
	ByID(id uint) (*User, error)
	ByEmail(email string) (*User, error)
	ByRemember(token string) (*User, error)

	//Methods for altering users
	Create(user *User) error
	Update(user *User) error
	Delete(id uint) error

	// Used to close a DB connection
	Close() error

	// Migration helpers
	AutoMigrate() error
	DestructiveReset() error
}

// UserService is a set of methods used to manipulate and
// work with the user model
type UserService interface {
	// Authenticate will verify tha provided email address and
	// password are correct. If they are correct, the user
	// corresponding to the email will be returned. Otherwise
	// You will recieve either:
	// ErrNotFound, ErrInvalidPassword, or another err if
	// something goes wrong.
	Authenticate(email, password string) (*User, error)
	UserDB
}

type User struct {
	gorm.Model
	Name         string
	Email        string `gorm:"not null;unique_index"`
	Password     string `gorm:"-"`
	PasswordHash string `gorm:"not null"`
	Remember     string `gorm:"-"`
	RememberHash string `gorm:"not null;unique_index`
}

type userService struct {
	UserDB
}

type userValFn func(*User) error

func runUserValFns(user *User, fns ...userValFn) error {
	for _, fn := range fns {
		if err := fn(user); err != nil {
			return err
		}
	}
	return nil
}

// bcryptPassword will hash a user's password with an
// app-wide peper and bcrypt, which salts for us
func (uv *userValidator) bcryptPassword(user *User) error {
	if user.Password == "" {
		// we don't need to run this if the password hasn't changed
		return nil
	}
	pwBytes := []byte(user.Password + userPwPepper)
	hashedBytes, err := bcrypt.GenerateFromPassword(pwBytes,
		bcrypt.DefaultCost)
	if err != nil {
		return err
	}
	user.PasswordHash = string(hashedBytes)
	user.Password = ""
	return nil
}

// hmacRemember will check if the remember is empty, if it is return nil
// if it is already set we hash it and put it in the user.RememberHash
func (uv *userValidator) hmacRemember(user *User) error {
	if user.Remember == "" {
		return nil
	}
	user.RememberHash = uv.hmac.Hash(user.Remember)
	return nil
}

// NewUserService takes the connection  info in as a string and
// returns a pointer to a UserService struct which for now
// holds the database info and the hmac info.
func NewUserService(connectionInfo string) (UserService, error) {
	ug, err := newUserGorm(connectionInfo)
	if err != nil {
		return nil, err
	}
	hmac := hash.NewHMAC(hmacSecretKey)
	uv := &userValidator{
		hmac:   hmac,
		UserDB: ug,
	}
	return &userService{
		UserDB: uv,
	}, nil
}

// userGorm represents our database inteaction layer
// and implements the UserDB interface fully.
type userGorm struct {
	db   *gorm.DB
	hmac hash.HMAC
}

// newUserGorm takes the connection  info in as a string and
// returns a pointer to a UserService struct which for now
// holds the database info and the hmac info.
func newUserGorm(connectionInfo string) (*userGorm, error) {
	db, err := gorm.Open("postgres", connectionInfo)
	if err != nil {
		return nil, err
	}
	db.LogMode(true)
	hmac := hash.NewHMAC(hmacSecretKey)
	return &userGorm{
		db:   db,
		hmac: hmac,
	}, nil
}

// userValidator is our validation layer that validates
// and normalizes data before passing it on to the nex
// UserDB in our interface chain.
type userValidator struct {
	UserDB
	hmac hash.HMAC
}

// Close closes the userGorm database connection
func (ug *userGorm) Close() error {
	return ug.db.Close()
}

// Create will create the item in the db
func (ug *userGorm) Create(user *User) error {
	return ug.db.Create(user).Error
}

// Create will create the provided user and backfill data
// like the ID, CreatedAt and UpdatedAt fields.
func (uv *userValidator) Create(user *User) error {
	err := runUserValFns(user,
		uv.bcryptPassword,
		uv.setRemeberIfUnset,
		uv.hmacRemember)
	if err != nil {
		return err
	}
	return uv.UserDB.Create(user)
}

// Update will hash a remember token if it is not provided.
func (uv *userValidator) Update(user *User) error {
	err := runUserValFns(user,
		uv.bcryptPassword,
		uv.hmacRemember)
	if err != nil {
		return err
	}
	return uv.UserDB.Update(user)
}

// setRemeberIfUnset checks to see if a Remember token is set and if not
// it sets one it returns an error
func (uv *userValidator) setRemeberIfUnset(user *User) error {
	if user.Remember != "" {
		return nil
	}
	token, err := rand.RememberToken()
	if err != nil {
		return err
	}
	user.Remember = token
	return nil
}

// Update will update the provided user with all of the data
// in the provied user object.
func (ug *userGorm) Update(user *User) error {
	return ug.db.Save(user).Error
}

// Delete will delete the user with the provided ID
// basically just checks to make sure the id is not 0
// and then hands it of to the userGorm Delete method
func (uv *userValidator) Delete(id uint) error {
	if id == 0 {
		return ErrIDInvalid
	}
	return uv.UserDB.Delete(id)
}

// Delete will delete the user with the provided ID
func (ug *userGorm) Delete(id uint) error {
	user := User{Model: gorm.Model{ID: id}}
	return ug.db.Delete(&user).Error
}

// ByID will look up a user with the provided ID.
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFoound
// If theree is another error, we will return an error with
// more information about what went wrong. This may not be
// an error generated by the models package.
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (ug *userGorm) ByID(id uint) (*User, error) {
	var user User
	db := ug.db.Where("id = ?", id)
	err := first(db, &user)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// ByEmail looks up a user with the given email address and
// returns the user.
// If the user is found, we will return a nil error
// if the user is not foound, we will return ErrNotFound
// If there is another error, we will return and error with
// more information about whatt went wrong. This may not be
// an error generated by the models package.
func (ug *userGorm) ByEmail(email string) (*User, error) {
	var user User
	db := ug.db.Where("email = ?", email)
	err := first(db, &user)
	return &user, err
}

// ByRemember looks up a user with the given remember token
// and returns that user.  This method will handle hashing the
// token for us.
// If the user is found, we will return a nil error
// if the user is not foound, we will return ErrNotFound
// If there is another error, we will return and error with
// more information about whatt went wrong. This may not be
// an error generated by the models package.
func (ug *userGorm) ByRemember(rememberHash string) (*User, error) {
	var user User
	err := first(ug.db.Where("remember_hash = ?", rememberHash), &user)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// ByRemember will hash the remember token and then call
// ByRemember on the subsequent UserDB Layer.
func (uv *userValidator) ByRemember(token string) (*User, error) {
	// create a dummy user with just a token
	user := User{
		Remember: token,
	}
	// run the normalizer hmacRemember which will hash the thing
	if err := runUserValFns(&user, uv.hmacRemember); err != nil {
		return nil, err
	}
	// access the hashed token that uv.hmacRemember put in the user object
	return uv.UserDB.ByRemember(user.RememberHash)
}

// Authenticate can be used to authenticate a user with the
// provided email address and password.
// If the email address provided is invalid, this will return
//	nil, ErrNotFound
// If the password provided is invallid, this will return
//	nil, ErrIvalidPassword
// If the email and password are both valid, this will return
//  user, nil
// Otherwise if another error is encountered this will return
//  nil, error
func (us *userService) Authenticate(email, password string) (*User, error) {
	foundUser, err := us.ByEmail(email)
	if err != nil {
		return nil, err
	}
	err = bcrypt.CompareHashAndPassword(
		[]byte(foundUser.PasswordHash),
		[]byte(password+userPwPepper))

	switch err {
	case nil:
		return foundUser, nil
	case bcrypt.ErrMismatchedHashAndPassword:
		return nil, ErrPasswordIncorrect
	default:
		return nil, err
	}
}

// AutoMigrate will attempt to automatically migrate the
// users table
func (ug *userGorm) AutoMigrate() error {
	if err := ug.db.AutoMigrate(&User{}).Error; err != nil {
		return err
	}
	return nil
}

// DestructiveReset ddrops the user table and rebuilds it
func (ug *userGorm) DestructiveReset() error {
	err := ug.db.DropTableIfExists(&User{}).Error
	if err != nil {
		return err
	}
	return ug.AutoMigrate()
}

// first will query using the provided gorm.DB and it will
// get the first item returned and place it into dst. If
// nothing is found in the query, it return ErrNotFound
func first(db *gorm.DB, dst interface{}) error {
	err := db.First(dst).Error
	if err == gorm.ErrRecordNotFound {
		return ErrNotFound
	}
	return err
}
